### ISSUE TITLE
cannot import name 'ForkingTCPServer'

### ISSUE THREAD

**Issue by Danielydsm** [johnhuang-cn/jpserve#4]
@johnhuang-cn when I tried to call from jpserve.jpserve import JPServe. Spider gives me the following error:
from jpserve.jpserve import JPServe
Traceback (most recent call last):

File "", line 1, in 
from jpserve.jpserve import JPServe

File "C:\ProgramData\Anaconda3\lib\site-packages\jpserve_init_.py", line 1, in 
from .jpserve import JPServe

File "C:\ProgramData\Anaconda3\lib\site-packages\jpserve\jpserve.py", line 38, in 
from socketserver import StreamRequestHandler, ThreadingTCPServer, ForkingTCPServer

ImportError: cannot import name 'ForkingTCPServer'

Can you help me?

**Comment by sandeeptiwari32** [comment]
i am also facing same issue. can you please provide any solution.

 import jpserve.jpserve as jp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\python\lib\site-packages\jpserve\__init__.py", line 1, in <module>
    from .jpserve import JPServe
  File "D:\python\lib\site-packages\jpserve\jpserve.py", line 38, in <module>
    from socketserver import StreamRequestHandler, ThreadingTCPServer, ForkingTCPServer
**ImportError: cannot import name 'ForkingTCPServer'**

**Comment by khamarshaikh** [comment]
you need to import the package using python3 , the package faces issue with python 2

**Comment by khamarshaikh** [comment]
Can someone help me with java side scripting  ,i am new to the usage . Please post a complete java usage file

**Comment by neilmfrench** [comment]
@Danielydsm @sandeeptiwari32 you need to be using python3 and running it on a unix machine - it relies on fork()

**Comment by raghucssit** [comment]
I am also facing the same issue. It seems this library works only on UNIX platform
